### PR TITLE
Changes and Tweaks at Behest of MNK

### PR DESCRIPTION
**Pull request by paulmadore**
Interested to know the purpose of the json file in /data.

### CODE REVIEW

**Comment by matthewjamesr** [comment]
@paulmadore Welcome to the Age of Chains party! Accepted the PR with some minor CSS changes, spacing, etc.

The JSON file is temp right now, I was exploring a possibility to make it easy for MNK to input updates easily on his own (no programming skills). Kind of stopped working it due to other areas of concern.

Are you in Counterparty slack?

**Comment by paulmadore** [comment]
No I'm not, I'm in Age slack tho

**Comment by matthewjamesr** [comment]
Great, I will chat you at some point tonight.

**Comment by paulmadore** [comment]
As regards an easy update, he could write plain text updates and we could
use JQuery to display

**Comment by matthewjamesr** [comment]
That is true, but I think tiny changes on formatting from his side could be of concern. Best method to future-proof is migrate from static Github Pages to custom Rails implementation. We have discussed this at length and are in agreement, it is just at the point of "who is paying" for the Digital Ocean droplet.

We could go free dyno for now at Heroku, but would create a bad experience with load times.

**Comment by paulmadore** [comment]
Overhead for little benefit. Interested to know overall motivations.

**Pull request merged**
